<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Yuri&#039;s Test Suite" duration-ms="26" started-at="2015-12-22T12:48:55Z" finished-at="2015-12-22T12:48:55Z">
    <groups>
    </groups>
    <test name="GMail tests" duration-ms="26" started-at="2015-12-22T12:48:55Z" finished-at="2015-12-22T12:48:55Z">
      <class name="by.epam.tat.cherevach.module5.webdriver.GMailOperations">
        <test-method status="SKIP" signature="logInGeneral(java.lang.String, java.lang.String)[pri:0, instance:null]" name="logInGeneral" duration-ms="0" started-at="2015-12-22T15:48:55Z" description="Fail login" data-provider="FailLoginProvider" finished-at="2015-12-22T15:48:55Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Can't invoke public java.lang.Object[][] by.epam.tat.cherevach.module5.webdriver.GMailOperations.valuesForFailLogin(): either make it static or add a no-args constructor to your class]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Can't invoke public java.lang.Object[][] by.epam.tat.cherevach.module5.webdriver.GMailOperations.valuesForFailLogin(): either make it static or add a no-args constructor to your class
	at org.testng.internal.Utils.checkInstanceOrStatic(Utils.java:800)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:42)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1246)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1171)
	at org.testng.TestNG.run(TestNG.java:1066)
	at by.epam.tat.cherevach.module5.webdriver.GMailTestRunner.main(GMailTestRunner.java:41)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logInGeneral -->
        <test-method status="FAIL" signature="logInPass()[pri:0, instance:null]" name="logInPass" duration-ms="5" started-at="2015-12-22T15:48:55Z" description="Pass login" finished-at="2015-12-22T15:48:55Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Can't invoke public void by.epam.tat.cherevach.module5.webdriver.GMailOperations.logInPass(): either make it static or add a no-args constructor to your class]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Can't invoke public void by.epam.tat.cherevach.module5.webdriver.GMailOperations.logInPass(): either make it static or add a no-args constructor to your class
	at org.testng.internal.Utils.checkInstanceOrStatic(Utils.java:800)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:42)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1246)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1171)
	at org.testng.TestNG.run(TestNG.java:1066)
	at by.epam.tat.cherevach.module5.webdriver.GMailTestRunner.main(GMailTestRunner.java:41)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logInPass -->
        <test-method name="sendEmail" signature="sendEmail(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:null]" status="SKIP" duration-ms="0" finished-at="2015-12-22T15:48:55Z" started-at="2015-12-22T15:48:55Z" depends-on-methods="by.epam.tat.cherevach.module5.webdriver.GMailOperations.logInPass" data-provider="=SendingEmailProvider" description="Sending email">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method GMailOperations.sendEmail(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:null] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method GMailOperations.sendEmail(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:null] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1246)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1171)
	at org.testng.TestNG.run(TestNG.java:1066)
	at by.epam.tat.cherevach.module5.webdriver.GMailTestRunner.main(GMailTestRunner.java:41)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sendEmail -->
        <test-method name="emailReceived" signature="emailReceived(java.lang.String, java.lang.String)[pri:0, instance:null]" status="SKIP" duration-ms="0" finished-at="2015-12-22T15:48:55Z" started-at="2015-12-22T15:48:55Z" depends-on-methods="by.epam.tat.cherevach.module5.webdriver.GMailOperations.sendEmail" data-provider="EmailReceivedProvider" description="Email received">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method GMailOperations.emailReceived(java.lang.String, java.lang.String)[pri:0, instance:null] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method GMailOperations.emailReceived(java.lang.String, java.lang.String)[pri:0, instance:null] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1246)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1171)
	at org.testng.TestNG.run(TestNG.java:1066)
	at by.epam.tat.cherevach.module5.webdriver.GMailTestRunner.main(GMailTestRunner.java:41)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emailReceived -->
        <test-method status="FAIL" signature="logout()[pri:0, instance:null]" name="logout" is-config="true" duration-ms="0" started-at="2015-12-22T15:48:55Z" finished-at="2015-12-22T15:48:55Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:182)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.afterRun(TestRunner.java:1033)
	at org.testng.TestRunner.run(TestRunner.java:636)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1246)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1171)
	at org.testng.TestNG.run(TestNG.java:1066)
	at by.epam.tat.cherevach.module5.webdriver.GMailTestRunner.main(GMailTestRunner.java:41)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="FAIL" signature="quit()[pri:0, instance:null]" name="quit" is-config="true" duration-ms="0" started-at="2015-12-22T15:48:55Z" finished-at="2015-12-22T15:48:55Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:182)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.afterRun(TestRunner.java:1033)
	at org.testng.TestRunner.run(TestRunner.java:636)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1246)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1171)
	at org.testng.TestNG.run(TestNG.java:1066)
	at by.epam.tat.cherevach.module5.webdriver.GMailTestRunner.main(GMailTestRunner.java:41)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- by.epam.tat.cherevach.module5.webdriver.GMailOperations -->
    </test> <!-- GMail tests -->
  </suite> <!-- Yuri's Test Suite -->
</testng-results>
